/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Limite;

import Control.ControlChocan;
import Entidad.ChocAn;
import Entidad.Miembro;
import Entidad.Proveedor;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Brayan
 */
public class InterfazOperador extends javax.swing.JFrame {

    /**
     * Creates new form Operador
     */
    public InterfazOperador() {
        initComponents();
        //----------------------------
        /*
        this.fila = new String[4];
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CORREO");
        modelo.addColumn("ESTADO");
        */
        this.fila = new String[7];
        modelo.addColumn("ID");
        modelo.addColumn("NOMBRE");
        modelo.addColumn("CORREO");
        modelo.addColumn("ESTADO");
        modelo.addColumn("DIRECCION");
        modelo.addColumn("CIUDAD");
        modelo.addColumn("CODIGO ZIP");
        //------------------------------
        this.jRadioButtonMiembro.setSelected(true);
        this.jRadioButtonProveedor.setSelected(true);
        
        if(this.jRadioButtonProveedor.isSelected()==true){
            this.controlChocan.leerArchivo("Proveedor");
            this.llenarTabla();
        }
        
        if(this.jRadioButtonMiembro.isSelected()==true){
            this.controlChocan.leerArchivo("Miembro");
            this.llenarTabla();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jRadioButtonMiembro = new javax.swing.JRadioButton();
        jRadioButtonProveedor = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jButtonBuscar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButtonInsertar = new javax.swing.JButton();
        jButtonBorrar = new javax.swing.JButton();
        jTextFieldEmail = new javax.swing.JTextField();
        jTextFieldNombre = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jButtonGuardar = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jTextFieldDireccion = new javax.swing.JTextField();
        jTextFieldCiudad = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTextFieldZip = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("GESTIÓN DE REGISTROS");

        jLabel2.setText("Si va a actuallizar o elimina datos de un registro existente.");

        jLabel3.setText("Escriba el numero del miembro o proveedor y preciones buscar.");

        jLabel4.setText("Si va a crear un registro nevo, llene el formulario y precione guardar.");

        jRadioButtonMiembro.setText("MIEMBRO");
        jRadioButtonMiembro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonMiembroActionPerformed(evt);
            }
        });

        jRadioButtonProveedor.setSelected(true);
        jRadioButtonProveedor.setText("PROVEEDOR");
        jRadioButtonProveedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButtonProveedorActionPerformed(evt);
            }
        });

        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
        });

        jButtonBuscar.setText("BUSCAR");
        jButtonBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBuscarActionPerformed(evt);
            }
        });

        jLabel5.setText("Nombre");

        jLabel7.setText("E-mail");

        jButtonInsertar.setText("INSERTAR");
        jButtonInsertar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonInsertarActionPerformed(evt);
            }
        });
        jButtonInsertar.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jButtonInsertarKeyPressed(evt);
            }
        });

        jButtonBorrar.setText("BORRAR");
        jButtonBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Miembro", "Proveedor" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel8.setText("Puesto");

        jButtonGuardar.setText("GUARDAR");
        jButtonGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonGuardarActionPerformed(evt);
            }
        });

        jLabel9.setText("Direccion");

        jLabel10.setText("Ciudad");

        jLabel11.setText("Codigo Zip");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(4, 4, 4)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel8)
                                .addComponent(jLabel11)
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel9)
                                .addComponent(jLabel7)
                                .addComponent(jLabel5))
                            .addGap(18, 18, 18)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTextFieldZip)
                                .addComponent(jTextFieldCiudad)
                                .addComponent(jTextFieldEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 105, Short.MAX_VALUE)
                                .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.Alignment.TRAILING)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(72, 72, 72)
                            .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jButtonInsertar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                    .addComponent(jButtonBorrar)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButtonGuardar))))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextFieldCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextFieldZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonInsertar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonBorrar)
                    .addComponent(jButtonGuardar))
                .addGap(30, 30, 30))
        );

        jTable1.setModel(modelo);
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jRadioButtonMiembro)
                .addGap(18, 18, 18)
                .addComponent(jRadioButtonProveedor)
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jButtonBuscar)
                .addGap(190, 190, 190))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 729, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jRadioButtonProveedor)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonBuscar)
                    .addComponent(jRadioButtonMiembro))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBuscarActionPerformed
            this.jRadioButtonMiembro.setSelected(false);
            this.jRadioButtonProveedor.setSelected(false);
        try{
            this.controlChocan.llenarLista(this.modelo);
            this.controlChocan.guardarArchivo("Miembro");
            this.controlChocan.guardarArchivo("Proveedor");
            this.vaciartabla();
            this.llenarTabla();
            this.vaciartabla();
            modelo.addRow(controlChocan.buscar(Integer.valueOf(this.jTextField1.getText())));
            
        }catch(Exception e){
            JOptionPane.showMessageDialog(this, "Error Numero no Existe", "ERROR", WIDTH);
        }
    }//GEN-LAST:event_jButtonBuscarActionPerformed

    public void insertar(){
    
        if(this.jTextFieldNombre.getText().length() > 2 && this.jTextFieldEmail.getText().length() > 6){
            if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Miembro")){
                ChocAn.listaMiembro.add(new Miembro(this.controlChocan.codigo(this.jComboBox1.getSelectedItem().toString()),
                        this.jTextFieldNombre.getText(),
                        this.jTextFieldEmail.getText(),
                        this.jTextFieldDireccion.getText(),
                        this.jTextFieldCiudad.getText(),Integer.valueOf(this.jTextFieldZip.getText()),"Activado")
                );
            }else if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Proveedor")){
                ChocAn.listaProveedor.add(new Proveedor(this.controlChocan.codigo(this.jComboBox1.getSelectedItem().toString()),
                        this.jTextFieldNombre.getText(),this.jTextFieldEmail.getText(),
                        this.jTextFieldDireccion.getText(),
                        this.jTextFieldCiudad.getText(),Integer.valueOf(this.jTextFieldZip.getText()))
                );
            }
        }
    }
    
    private void jButtonInsertarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonInsertarActionPerformed
        this.vaciartabla();
        this.insertar();
        this.llenarTabla();
            this.jTextFieldEmail.setText("");
            this.jTextFieldNombre.setText("");
            this.jTextFieldDireccion.setText("");
            this.jTextFieldCiudad.setText("");
            this.jTextFieldZip.setText("");
            this.controlChocan.llenarLista(this.modelo);
        this.controlChocan.guardarArchivo("Miembro");
        this.controlChocan.guardarArchivo("Proveedor");
        this.vaciartabla();
        this.llenarTabla();
    }//GEN-LAST:event_jButtonInsertarActionPerformed

    private void jButtonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonGuardarActionPerformed
        this.controlChocan.llenarLista(this.modelo);
        this.controlChocan.guardarArchivo("Miembro");
        this.controlChocan.guardarArchivo("Proveedor");
        this.vaciartabla();
        this.llenarTabla();
    }//GEN-LAST:event_jButtonGuardarActionPerformed

    public void llenarTabla(){
        this.vaciartabla();
        
        if(this.jRadioButtonMiembro.isSelected()==true){
            for (int i = 0; i < ChocAn.listaMiembro.size(); i++) {
                String[] fila={
                    String.valueOf(ChocAn.listaMiembro.get(i).getNumero()),
                    ChocAn.listaMiembro.get(i).getNombre(),
                    ChocAn.listaMiembro.get(i).getEmail(),
                    String.valueOf(ChocAn.listaMiembro.get(i).getEstado()),
                    ChocAn.listaMiembro.get(i).getDireccion(),
                    ChocAn.listaMiembro.get(i).getCiudad(),
                    String.valueOf(ChocAn.listaMiembro.get(i).getZip())
                };
                modelo.addRow(fila);
            }
        }
        
        if(this.jRadioButtonProveedor.isSelected()==true){
            for (int i = 0; i < ChocAn.listaProveedor.size(); i++) {
                String[] fila={
                    String.valueOf(ChocAn.listaProveedor.get(i).getNumero()),
                    ChocAn.listaProveedor.get(i).getNombre(),
                    ChocAn.listaProveedor.get(i).getEmail(),
                    "",
                    ChocAn.listaProveedor.get(i).getDireccion(),
                    ChocAn.listaProveedor.get(i).getCiudad(),
                    String.valueOf(ChocAn.listaProveedor.get(i).getZip())
                };
                modelo.addRow(fila);
            }
        }
    }
    
    private void jRadioButtonProveedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonProveedorActionPerformed
        this.llenarTabla();
    }//GEN-LAST:event_jRadioButtonProveedorActionPerformed
    
    private void jRadioButtonMiembroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButtonMiembroActionPerformed
        
        this.llenarTabla();
    }//GEN-LAST:event_jRadioButtonMiembroActionPerformed

    private void jButtonBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarActionPerformed
        if(JOptionPane.showConfirmDialog(this, "Esta Seguro que desea Eliminar el registro", "Confirmar",JOptionPane.YES_NO_OPTION)==0)
        {
          try{  
            this.controlChocan.eliminarCodigo(Integer.valueOf(this.modelo.getValueAt(this.jTable1.getSelectedRow(), 0).toString()));
            this.controlChocan.llenarLista(this.modelo);
            this.controlChocan.guardarArchivo("Miembro");
            this.controlChocan.guardarArchivo("Proveedor");
            this.vaciartabla();
            this.llenarTabla();
          }catch(Exception e ){
              JOptionPane.showMessageDialog(this, "Debe de seleccionar un registro", "ERROR", WIDTH);
          }
        
        }
    }//GEN-LAST:event_jButtonBorrarActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Miembro")){
            this.jRadioButtonMiembro.setSelected(true);
        }
        if(this.jComboBox1.getSelectedItem().toString().equalsIgnoreCase("Proveedor")){
            this.jRadioButtonProveedor.setSelected(true);
        }
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if(evt.getKeyCode()==10){
            this.vaciartabla();
            modelo.addRow(controlChocan.buscar(Integer.valueOf(this.jTextField1.getText())));
            this.jRadioButtonMiembro.setSelected(false);
            this.jRadioButtonProveedor.setSelected(false);
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed
        if(evt.getKeyCode()==127){
            if(JOptionPane.showConfirmDialog(this, "Esta Seguro que desea Eliminar el registro", "Confirmar",JOptionPane.YES_NO_OPTION)==0)
            {
                this.controlChocan.eliminarCodigo(Integer.valueOf(this.modelo.getValueAt(this.jTable1.getSelectedRow(), 0).toString()));
                this.vaciartabla();
                this.llenarTabla();
                this.controlChocan.llenarLista(this.modelo);
                this.controlChocan.guardarArchivo("Miembro");
                this.controlChocan.guardarArchivo("Proveedor");
                this.vaciartabla();
                this.llenarTabla();
            }
        }
    }//GEN-LAST:event_jTable1KeyPressed

    private void jButtonInsertarKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jButtonInsertarKeyPressed
        if(evt.getKeyCode()==10){
            this.vaciartabla();
            this.insertar();
            this.llenarTabla();
            this.jTextFieldEmail.setText("");
            this.jTextFieldNombre.setText("");
            this.jTextFieldDireccion.setText("");
            this.jTextFieldCiudad.setText("");
            this.jTextFieldZip.setText("");
            this.controlChocan.llenarLista(this.modelo);
            this.controlChocan.guardarArchivo("Miembro");
            this.controlChocan.guardarArchivo("Proveedor");
            this.vaciartabla();
            this.llenarTabla();
        
        }
    }//GEN-LAST:event_jButtonInsertarKeyPressed
    public  DefaultTableModel modelo = new DefaultTableModel();
    public ControlChocan controlChocan = new ControlChocan();
    
    public String[] fila;
    public char[] datosFila;

    public DefaultTableModel getModelo() {
        return modelo;
    }

    public void setModelo(DefaultTableModel modelo) {
        this.modelo = modelo;
    }

    public JTable getjTable1() {
        return jTable1;
    }

    public void setjTable1(JTable jTable1) {
        this.jTable1 = jTable1;
    }
    
    
    
    public void vaciarFila(){
        for (int i = 0; i < this.fila.length; i++) {
            this.fila[i]="";
        }
    }
    
    public void vaciartabla(){
        int count=modelo.getRowCount();
        for (int i = 0; i < count; i++) {
            modelo.removeRow(0);//debe de ser 0 y no i por que si nosea terco piense
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazOperador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new InterfazOperador().setVisible(true);
            }
            
            
            
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorrar;
    private javax.swing.JButton jButtonBuscar;
    private javax.swing.JButton jButtonGuardar;
    private javax.swing.JButton jButtonInsertar;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jRadioButtonMiembro;
    private javax.swing.JRadioButton jRadioButtonProveedor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextFieldCiudad;
    private javax.swing.JTextField jTextFieldDireccion;
    private javax.swing.JTextField jTextFieldEmail;
    private javax.swing.JTextField jTextFieldNombre;
    private javax.swing.JTextField jTextFieldZip;
    // End of variables declaration//GEN-END:variables
}
